### ISSUE TITLE
Credit Slime Rancher in description for Slime-Pack

### ISSUE THREAD

**Issue by EMERALD0874** [DarkSide1305/AudioPacks#1]
Can you please update the description for Slime Pack to credit Slime Rancher as the source material? You don't have to make a PR for the Audio Loader database until you add another pack or something, it's just something I'd like to see done so we're better respecting the copyright owners.

**Comment by CaviarTheCatgirl** [comment]
Fixed, PR will be created shortly to fix that and include my new Music Pack
